services:
  matrix_synapse:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 8080:8080
    #    restart: always
    environment:
      SYNAPSE_SERVER_NAME: ${MATRIX_SERVER_NAME}
      SYNAPSE_REPORT_STATS: ${MATRIX_REPORT_STATS}
      VIRTUAL_HOST: ${MATRIX_HOST}
      VIRTUAL_PORT: ${MATRIX_PORT}
      LETSENCRYPT_HOST: ${MATRIX_HOST}
      LETSENCRYPT_EMAIL: zusel7.zusel7@gmail.com
    env_file:
      - .env
    depends_on:
      - siwe-oidc
      - proxy
    volumes:
      - matrix_data:/data

  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  siwe-oidc:
    image: ghcr.io/spruceid/siwe_oidc:20221208081605782143
    depends_on:
      - redis
    ports:
      - ${SIWEOIDC_PORT}:${SIWEOIDC_PORT}
    environment:
      SIWEOIDC_REDIS_URL: "redis://redis"
      SIWEOIDC_ADDRESS: ${SIWEOIDC_ADDRESS}
      SIWEOIDC_HOST: ${SIWEOIDC_HOST}
      SIWEOIDC_PORT: ${SIWEOIDC_PORT}
      SIWEOIDC_DEFAULT_CLIENTS: ${SIWEOIDC_DEFAULT_CLIENTS}
      SIWEOIDC_BASE_URL: ${SIWEOIDC_BASE_URL}
      RUST_LOG: ${RUST_LOG}
      VIRTUAL_HOST: ${SIWEOIDC_HOST}
      VIRTUAL_PORT: ${SIWEOIDC_PORT}
      LETSENCRYPT_HOST: ${SIWEOIDC_HOST}
      LETSENCRYPT_EMAIL: zusel7.zusel7@gmail.com

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: proxy_server_proxy_1
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy_data_conf_d:/etc/nginx/conf.d:rw
      - proxy_data_vhost_d:/etc/nginx/vhost.d:rw
      - proxy_data_html:/usr/share/nginx/html:rw
      - proxy_data_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- "./max_upload_size.conf:/etc/nginx/conf.d/max_upload_size.conf"
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: proxy_server_letsencrypt_1
    depends_on:
      - proxy
    volumes:
      - proxy_data_acme:/etc/acme.sh
      - proxy_data_conf_d:/etc/nginx/conf.d:rw
      - proxy_data_vhost_d:/etc/nginx/vhost.d:rw
      - proxy_data_html:/usr/share/nginx/html:rw
      - proxy_data_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped


volumes:
  matrix_data:
  proxy_data_acme:
  proxy_data_conf_d:
  proxy_data_vhost_d:
  proxy_data_html:
  proxy_data_certs:
